### ISSUE TITLE
Implement testing

### ISSUE THREAD

**Issue by brodeynewman** [otakustay/react-diff-view#10]
Right now, there are no tests written, and for future maintainability, testing will be needed.

Enzyme and snapshot tests should be implemented.

Istanbul coverage reports are also helpful.

**Comment by otakustay** [comment]
This project is in fact a combination of 2 libs

The first one is a utility to modify diff data structures (diff, hunk, change), this is simple javascript and all functions are pure, so it can be easily unit tested. The 10 patch version of `1.4.x` is a strong evidence of the importance of unit test,  I'm planning to add mocha tests to `util` module, a 100% coverage is possible. Due to it is currently the beginning of a Chinese year, I'm quite busy at company works, so contribution to this project will be delayed for some time, anyway this could happen **before April**

The second is a react component that visualize the diff data structure, this is not that easy to unit test, enzyme is a possible solution but I don't really think it could be that useful. Luckily all react components are quite simple (comparing to the util module), currently I tend to leave it to manual tests.

Further more, a performance measurement is also required since it is common sense for a diff to have thousands of lines, a big `<table>` element can be extremely laggy on any redundant component render

**Comment by otakustay** [comment]
Fixed via #20 and #21
