### ISSUE TITLE
Invalid `diffType` when parsing patch with new files

### ISSUE THREAD

**Issue by lucasbento** [otakustay/react-diff-view#49]
Hello,

First off, thank you so much for this library, we are using it heavily in [react-native upgrade-helper](https://github.com/react-native-community/upgrade-helper).

When parsing [this patch](https://raw.githubusercontent.com/react-native-community/rn-diff-purge/diffs/diffs/0.53.0..0.57.8.diff) which includes new files such as `android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png` it gives the following prop warning:

![image](https://user-images.githubusercontent.com/6207220/59333132-07abfa00-8cf8-11e9-8860-50611a9ee6f2.png)

This is caused because when parsing these new files it gives the `diff.type` as `new` instead of `add`. I simply used `type={diff.type === 'new' ? 'add' : diff.type}` as a workaround for this.

If you can point out where to fix this I can open a PR :)

**Comment by otakustay** [comment]
This is the first case we encountered diff for binary files, seems our diff parser fails to resolve the correct diff type from a binary section since it lacks the oldPath and newPath field.

I will have a deeper look at this issue, however even after I fixed this parsing issue, `react-diff-view` will not be able to visualize binary diffs, I recommend you to filter out binary files from filenames at first.

**Comment by lucasbento** [comment]
I'll try to keep `type={diff.type === 'new' ? 'add' : diff.type}` and see how that will go, I'm also defining if a diff is from a binary or not based on how many `hunks` it has, so if it's `0` then I categorize it as a binary.
