### ISSUE TITLE
Replace content on a per line basis

### ISSUE THREAD

**Issue by NathanBWaters** [otakustay/react-diff-view#55]
Hi @otakustay.  Yet again I want to say how great this library is.

Is it possible to edit content of a diff on a per-line basis?  Right now I'm only able to do it at a per-token basis.  This is good, but I actually want to replace text across two tokens.

For example, let's say I want a function headers in a diff to be clickable so that you can see more information about the function.  To do this, I'm using `markWord` and replacing the tokens that match a function name from a string to a component.

Because I'm only able to replace tokens, I can only replace the function name and not the whole signature.

Any advice on which direction I should go is much appreciated.

**Comment by otakustay** [comment]
As of version 2.x, there is a more low level tokenizing helper [pickRanges](https://github.com/otakustay/react-diff-view#pick-ranges) which perfectly fits your case

In order to archive this, you have to find:

1. The line number where your function signature is
2. The start index in that line
3. The length of your signature

For example we have a code like:

```js
import foo from './bar';

function wrappedBar(x, y) {
  return bar(x, y).map(i => i.toString());
};
```

We'd like to highlight `wrappedBar(x, y)`, so we find it in line `3`, starting at a index of `9` (`'function '.length`) with a length of `16` (`'wrappedBar(x, y)'.length`), so we make this range as:

```
{
  type: 'definition', // any thing your want
  lineNumber: 3,
  start: 9,
  length: 16,
  // custom properties
  properties: {
    tokenType: 'function',
    functionName: 'wrappedBar'
  }
}
```

By invoking `pickRanges` we can get an enhancer:

```
enhancers: [
  markEdits(hunks),
  pickRanges(oldRanges, newRanges)
]
```

`oldRanges` are those you want to pick out on the left side, `newRanges` on the right side.

Then you need to create a custom `renderToken` function and pass it to `Diff` component as illustrated in README, we can even add `onClick` to spans in `renderToken` function.

Since codesandbox cannot handle web workers, I cannot currently provide a working demo for you, will try to find a way to host a more complete demo including function definition highlights.

**Comment by NathanBWaters** [comment]
Thanks so much for the guidance!  I'll give it a shot and will report back once I've succeeded.
