### ISSUE TITLE
Ability to wrap a single line of output in a component

### ISSUE THREAD

**Issue by bobsilverberg** [otakustay/react-diff-view#70]
Firs off, thank you for this excellent library. We are using it extensively in our code review app.

We have come across a requirement to wrap the `<tr>` tags that are generated for each line in the diff in a custom component. There doesn't seem to be a way to do that currently. This would be something similar to the [customize gutter](https://github.com/otakustay/react-diff-view/blob/master/README.md#customize-gutter) functionality, in that it would provide access to the default `<tr>` that would be rendered and allow one to wrap anything around it.

Is that something you'd consider implementing?

**Comment by otakustay** [comment]
To create a component **around** `<tr>` tag is currently impossible, a `<tbody>` element can only contain `<tr>` elements, however it is possible to wrap everything inside `<tr>` into a custom component via our tokenization system:  https://codesandbox.io/s/react-diff-view70-0hyqb

**Comment by bobsilverberg** [comment]
> To create a component **around** `<tr>` tag is currently impossible, a `<tbody>` element can only contain `<tr>` elements, however it is possible to wrap everything inside `<tr>` into a custom component via our tokenization system: [codesandbox.io/s/react-diff-view70-0hyqb](https://codesandbox.io/s/react-diff-view70-0hyqb)

Thanks for your response @otakustay. Yes, you are correct that HTML will not allow us to wrap something **around** a `<tr>` tag, and what I was looking for was the ability to wrap something around everything that would be rendered **inside** the `<tr>` tag, as you suggested.

I took a look at the example and it does get me partway there, except for the following issues:

1. It only allows me to wrap the content of the code that would be rendered, and it does not allow me to wrap the entire contents of the the `<tr>` tag including the gutter. I could get around this by using both `renderToken` and `renderGutter`, but it would be nice to be able to achieve the wrapping of the entire line with a single function.

2. I need access to information about the `change` inside the `renderToken` function, in the same way that the `change` is available inside the `renderGutter` function. I need this information to pass into the component that I wish to wrap around the contents that are being generated. Is that something you would consider adding?

**Comment by otakustay** [comment]
> 1. It only allows me to wrap the content of the code that would be rendered, and it does not allow me to wrap the entire contents of the the `<tr>` tag including the gutter

This component's table layout is fixed for performance reasons and is related to `hideGutter` and `viewType` props, it could be 2, 3 or 4 columns.

In this case I don't recommend you to create everything inside `<tr>` since:

1. You will be forced to comply `hideGutter` and `viewType` props to decide how many `<td>` elements could be rendered, but this is an internal implement of component and could be changed in future minor releases, for example I may add another prop to remove some `<td>` or add some extra cells.
2. This can be conflict with `renderGutter` and `renderToken`, it will be very difficult for users to understand which get priority over which.

I'd recommend to combine `renderToken` and `renderGutter` to archive customization.

> 2. I need access to information about the `change` inside the `renderToken` function

This is simple, put `change` into `properties` when reduce changes into tokens in `wrapInCustom` function from my demo, then it is available as `token.change` in `renderToken`.

The `properties` can hold everything and will be merged into `token` object.
