### ISSUE TITLE
Add support for drag-start and drag-end events

### ISSUE THREAD

**Issue by siddhant1** [otakustay/react-diff-view#77]
We should add support for supporting gutter events on multiple lines

**Comment by dancerphil** [comment]
Sounds great!
PR is welcome if you interested in raising one.

**Comment by siddhant1** [comment]
dont close!

**Comment by otakustay** [comment]
For gutters only, I think we have already exposed `renderGutter` function prop so that you can render it with draggable and droppable hocs, if any functionality should be supported, please have a more detailed description

If it is a problem about the total complexity using `renderGutter`, we may support this via document or demo sandbox
