### ISSUE TITLE
The spilt diff viewer behaves like unified view

### ISSUE THREAD

**Issue by siddhant1** [otakustay/react-diff-view#78]
The spilt diff viewer behaves like unified view when there are  only additions

**Comment by otakustay** [comment]
This is a screenshot I captured with only additions and I think this works as expected because github also works like this:

![image](https://user-images.githubusercontent.com/639549/74129020-8788bc00-4c19-11ea-99a7-5f113e16bc31.png)

Can you give a more explanation on what you want to see in this case?

**Comment by siddhant1** [comment]
Sorry, my bad!
